services:
  database:
    extends:
      file: common.yml
      service: database

  backend:
    extends:
      file: common.yml
      service: backend
    build: backend
    healthcheck:
      test: "curl --fail localhost:8000/openapi.json || exit 1"
      interval: 5s
      timeout: 10s
      retries: 12
    depends_on:
      database:
        condition: service_healthy

  runner:
    extends:
      file: common.yml
      service: runner
    build: backend
    depends_on:
      backend:
        condition: service_healthy

  nginx:
    build:
      context: .
      args:
        - ALGOBATTLE_DB_PW=${ALGOBATTLE_DB_PW}
        - ALGOBATTLE_BASE_URL=${ALGOBATTLE_BASE_URL}
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:
    # intentionally empty
  db-files:
    # intentionally empty
