services:
  database:
    image: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
    healthcheck:
      test: "mysqladmin ping"
      interval: 2s
      timeout: 20s
      retries: 10
    volumes:
      - db-data:/var/lib/mysql
  backend:
    build: backend
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: "curl --fail localhost:8000/openapi.json || exit 1"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - TZ=Europe/Berlin
      - SQL_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./config.toml:/algobattle/config.toml
      - db-files:/algobattle/dbfiles
  runner:
    build: backend
    command: algobattle_runner
    stop_grace_period: 1s
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ALGOBATTLE_IO_VOLUMES=true
      - TZ=Europe/Berlin
      - SQL_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./config.toml:/algobattle/config.toml
      - db-files:/algobattle/dbfiles
      - /var/run/docker.sock,target=/var/run/docker.sock
      - algobattle_input:/algobattle/input
      - algobattle_output:/algobattle/output
  nginx:
    build: .
    depends_on:
      database:
        condition: service_healthy
      backend:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:
    # intentionally empty
  db-files:
    # intentionally empty
  algobattle_input:
    external: true
  algobattle_output:
    external: true
