services:
  database:
    extends:
      file: common.yml
      service: database

  backend:
    extends:
      file: common.yml
      service: backend
    build: backend
    depends_on:
      database:
        condition: service_healthy

  runner:
    extends:
      file: common.yml
      service: runner
    build: backend
    depends_on:
      backend:
        condition: service_started

  nginx:
    build:
      context: .
      args:
        - ALGOBATTLE_DB_PW=${ALGOBATTLE_DB_PW}
        - ALGOBATTLE_BASE_URL=${ALGOBATTLE_BASE_URL}
    depends_on:
      backend:
        condition: service_started
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure

volumes:
  db-data:
    # intentionally empty
  db-files:
    # intentionally empty
