services:
  backend:
    build: backend
    ports:
      - ":8000"
    environment:
      - ALGOBATTLE_CONFIG_PATH=/config/config.toml
    volumes:
      - ./config.toml:/config/config.toml
  nginx:
    build: .
    ports:
      - ":8000"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
