[project]
name = "algobattle_web"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Imogen Hergeth"}, {name = "Henri Lotze"}]
urls = {github = "https://github.com/Benezivas/algobattle-web"}
classifiers = [
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    "algobattle-base",
    "uvicorn",
    # until https://github.com/tiangolo/fastapi/pull/5978 is accepted
    "fastapi @ git+https://github.com/ImogenBits/fastapi.git@pydantic_orm",
    "python-jose[cryptography]",
    "python-multipart",
    "sqlalchemy >= 2.0.0b1",
    "pydantic",
    "markdown",
]

[project.scripts]
algobattle_web = "algobattle_web.app:main"

[tool.setuptools]
packages = ["algobattle_web"]
